spring.application.name=MeditatiIO
# Configurare conexiune la PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/MeditatiioDB
spring.datasource.username=postgres
spring.datasource.password=2230

# Configurare JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=meditatiostorage;AccountKey=gLvn+6W44LeiQJ3iaqThsMYHLn5UD1NT11oIqg/JmsgDsSzBOyA3N5OLcMHZPAQ+/CpfOuCQndFK+ASts9lByg==;EndpointSuffix=core.windows.net
azure.storage.container-name=meditatiiocontainer


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.model=llama3

server.port=9090